name: Build, Push & Deploy FastAPI App

on: 
  push:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        no-cache: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest  # Make sure this tag is correct

  deploy:
    runs-on: ubuntu-latest
    needs: buildx

    steps:
    - name: Deploy to Remote Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /path/to/your/deployment/directory
          docker-compose pull
          docker-compose up -d --build
        EOF
